App_content/urls.py
from django.urls import path
from . import views

app_name = 'App_content'

urlpatterns = [
    path('', views.new_podcast, name='new_podcast'),
    path('pod-showcase/', views.podcast_listview, name='pod-showcase'),
    path('new-post/', views.new_post, name='new-post'),
    path('post-listview/', views.post_listview, name='post-listview'),
    path('post-react/<int:pk>/', views.post_react, name='post-react'),
    path('add-syllabus/', views.add_syllabus, name='add-syllabus'),
    path('syllabus-listview/', views.syllabus_listview, name='syllabus-listview'),
    path('send-request/<int:user_id>/', views.connection_request, name='cennection-request'),
    path('accept-request/<int:request_id>/', views.accept_connection_request, name='accept-request'),
]

App_post/urls.py
from django.urls import path
from . import views

app_name = 'App_post'

urlpatterns = [
    path('', views.home, name='home'),
    path('partner-request/', views.partner_request, name='partner-request'),
    path('job-post/', views.job_post, name='job-post'),
    path('display-requests/', views.display_partner_requests, name='display-requests'),
    path('apply/<int:pk>/', views.apply_for_participation, name='apply-for-participation')
]

WePoka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('posts/', include('App_post.urls')),
    path('content/', include('App_content.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_content/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class PodcastModel(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE, related_name='podcast_creator')
    title = models.CharField(max_length=800)
    description = models.TextField(blank=True, null=True)
    cover_image = models.ImageField(upload_to='podcast_images', blank=True, null=True)
    audio_file = models.FileField(upload_to='music', blank=False, null=False)
    created_on = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_on']


class PodcastLoveReact(models.Model):
    post = models.ForeignKey(PodcastModel, on_delete=models.CASCADE, related_name='liked_podcast')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='podcast_liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def str(self):
        return "{} : {}".format(self.user, self.post)


class PostsModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='resource_sharing')
    post_image1 = models.ImageField(upload_to='post_images', blank=True, null=True)
    post_image2 = models.ImageField(upload_to='post_images', blank=True, null=True)
    post_image3 = models.ImageField(upload_to='post_images', blank=True, null=True)
    my_text = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ["-created_on"]

    def str(self):
        return self.my_text


class PostLoveReact(models.Model):
    post = models.ForeignKey(PostsModel, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_liker')
    liked = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def str(self):
        return "{} : {}".format(self.user, self.post)

# -----------------------------syllabus--------------------------------------------#


class SyllabusModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='provider')
    university = models.CharField(max_length=200)
    department = models.CharField(max_length=300)
    session = models.CharField(max_length=100, blank=True, null=True)
    syllabus = models.FileField(upload_to='syllabuses', blank=False, null=False)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.university}-{self.department}-{self.session}"


# -----------------------------end syllabus--------------------------------------------#
# -------------------------------connections--------------------------------------------#


class ConnectionModel(models.Model):
    connections = models.ManyToManyField(User, blank=True)


class ConnectionRequestModel(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
    created_on = models.DateTimeField(auto_now_add=True)

App_content/views.py
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.models import User

# Create your views here.
from App_content.models import PodcastModel, PostsModel, PostLoveReact, SyllabusModel, ConnectionRequestModel


def new_podcast(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        cover_image = request.FILES.get('cover_image')
        audio_file = request.FILES.get('audio_file')
        description = request.POST.get('description')
        audio_model = PodcastModel(host=request.user, title=title, description=description, cover_image=cover_image,
                                   audio_file=audio_file)
        audio_model.save()
        return HttpResponseRedirect(reverse('App_post:home'))
    return render(request, 'App_content/add_podcast.html')


def podcast_listview(request):
    pod_list = PodcastModel.objects.filter(status=True)
    content = {
        'pod_list': pod_list,
    }
    return render(request, 'App_content/podcast_listview.html', context=content)


def new_post(request):
    if request.method == 'POST':
        post = request.POST.get('title')
        image1 = request.FILES.get('post_image1')
        image2 = request.FILES.get('post_image2')
        image3 = request.FILES.get('post_image3')
        post_model = PostsModel(author=request.user, post_image1=image1, post_image2=image2, post_image3=image3,
                                my_text=post)
        post_model.save()
        return HttpResponseRedirect(reverse('App_post:home'))
    return render(request, 'App_content/new_post.html')


def post_listview(request):
    post_list = PostsModel.objects.filter(status=True)
    content = {
        'post_list': post_list,
    }
    return render(request, 'App_content/post_listview.html', context=content)


def post_react(request, pk):
    post = PostsModel.objects.get(id=pk)
    try:
        react = PostLoveReact.objects.get(post=post, user=request.user)
        if react.liked is False:
            react.liked = True
            react.save()
        else:
            react.liked = False
            react.save()
    except Exception as e:
        react_model = PostLoveReact(post=post, user=request.user, liked=True)
        react_model.save()
    return HttpResponseRedirect(reverse('App_content:post-listview'))


# -----------------------------syllabus--------------------------------------------#

def add_syllabus(request):
    if request.method == 'POST':
        uni = request.POST.get('university')
        dept = request.POST.get('department')
        session = request.POST.get('session')
        syllabus = request.FILES.get('syllabus')
        syllabus_model = SyllabusModel(user=request.user, university=uni, department=dept, session=session,
                                       syllabus=syllabus)
        syllabus_model.save()
        return HttpResponseRedirect(reverse('App_post:home'))
    return render(request, 'App_content/add_syllabus.html')


def syllabus_listview(request):
    syllabuses = SyllabusModel.objects.filter(status=True)
    content = {
        'syllabuses': syllabuses,
    }
    return render(request, 'App_content/syllabus_listview.html', context=content)

# -----------------------------------------------connections---------------------------------------- #


def connection_request(request, user_id):
    from_user = request.user
    to_user = User.objects.get(id=user_id)
    connect_request, created = ConnectionRequestModel.objects.get_or_create(from_user=from_user, to_user=to_user)
    if created:
        return HttpResponse('Connection request sent')
    else:
        return HttpResponse('connection request was already sent')


def accept_connection_request(request, request_id):
    connect_request = ConnectionRequestModel.objects.get(id=request_id)
    if connect_request.to_user == request.user:
        connect_request.to_user.connections.add(connect_request.from_user)
        connect_request.from_user.connections.add(connect_request.to_user)
        connect_request.delete()
        return HttpResponse('connection request is accepted.')
    else:
        return HttpResponse('request is not accepted.')

templates/App_content/add_podcast.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Title</title>
    <style>
        html,
        body {
            height: 100%;
            background-image: url("{% static 'bg_dark.jpg' %}");
        }

        .container-fluid {
            padding: 2rem;
        }

        .card {
            color: #666b7a;
            font-weight: 600;
            border-width: 8px;
            border-color: #444857;
            background-color: #1d1e22;
        }

        .card-body {
            padding: 1rem 2rem;
        }

        .input-daterange > input {
            cursor: pointer;
            border-radius: 3px !important;
            text-align: inherit;
        }

        .form-radio {
            padding-top: 6px;
        }

        .radio-inline {
            font-weight: 500;
        }

        .form-check-input {
            width: 25px;
            height: 25px;
            margin: 0px 6px 2px;
            vertical-align: middle;
        }

        .input-group-text {
            border-right: 0px;
            background-color: #ffffff;
            border-radius: 0.25rem 0 0 0.25rem;
        }

        .input-username > .form-control {
            border-left: 0px;
            border-radius: 0 0.25rem 0.25rem 0;
        }


        @media (max-width: 767px) {
            .img-title {
                display: block;
            }
        }


    </style>
</head>
<body>
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title text-center">Release New Episode<span><a href="{% url 'App_post:home' %}"
                                                                           style="float: right; text-decoration: none; color: #666B7AFF">✖</a></span>
            </h4>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-lg-9 col-md-6 col-sm-12">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title"
                               placeholder="Topic of discussion"/>
                    </div>

                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                        <label for="cover_image">Cover Image</label>
                            <input type="file" class="form-control" id="cover_image"
                                   name="cover_image"/>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                        <label for="audio_file" class="form-label">Podcast File</label>
                        <input type="file" class="form-control" id="audio_file" name="audio_file">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                        <label for="description" class="form-label">Thoughts</label>
                        <textarea type="text" class="form-control" id="description" name="description"
                                  placeholder="What's In your mind???" rows="3"></textarea>
                    </div>

                </div>
                <hr>
                <button class="w-100 btn btn-secondary btn-lg" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

templates/App_content/add_syllabus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Title</title>
    <style>
        html,
        body {
            height: 100%;
            background-image: url("{% static 'bg_dark.jpg' %}");
        }

        .container-fluid {
            padding: 2rem;
        }

        .card {
            color: #666b7a;
            font-weight: 600;
            border-width: 8px;
            border-color: #444857;
            background-color: #1d1e22;
        }

        .card-body {
            padding: 1rem 2rem;
        }

        .input-daterange > input {
            cursor: pointer;
            border-radius: 3px !important;
            text-align: inherit;
        }

        .form-radio {
            padding-top: 6px;
        }

        .radio-inline {
            font-weight: 500;
        }

        .form-check-input {
            width: 25px;
            height: 25px;
            margin: 0px 6px 2px;
            vertical-align: middle;
        }

        .input-group-text {
            border-right: 0px;
            background-color: #ffffff;
            border-radius: 0.25rem 0 0 0.25rem;
        }

        .input-username > .form-control {
            border-left: 0px;
            border-radius: 0 0.25rem 0.25rem 0;
        }


        @media (max-width: 767px) {
            .img-title {
                display: block;
            }
        }


    </style>
</head>
<body>
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title text-center">Release New Episode<span><a href="{% url 'App_post:home' %}"
                                                                           style="float: right; text-decoration: none; color: #666B7AFF">✖</a></span>
            </h4>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label for="university">University</label>
                        <input type="text" class="form-control" id="university" name="university"
                               placeholder="Name of the university"/>
                    </div>
                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label for="department">Department</label>
                        <input type="text" class="form-control" id="department" name="department"
                               placeholder="Example: CSE"/>
                    </div>
                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label for="session">Session</label>
                        <input type="text" class="form-control" id="session" name="session"
                               placeholder="Example: 2016-17"/>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                        <label for="syllabus" class="form-label">Syllabus (pdf/doc/ppt ect...)</label>
                        <input type="file" class="form-control" id="syllabus" name="syllabus">
                    </div>
                </div>
                <hr>
                <button class="w-100 btn btn-secondary btn-lg" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

templates/App_content/post_listview.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Title</title>
    <style>
        html,
        body {
            height: 100%;
            background-image: url("{% static 'bg_dark.jpg' %}");
        }

        .container-fluid {
            padding: 2rem;
        }

        .card {
            color: #666b7a;
            font-weight: 600;
            border-width: 8px;
            border-color: #444857;
            background-color: #1d1e22;
        }

        .card-body {
            padding: 1rem 2rem;
        }

        .input-daterange > input {
            cursor: pointer;
            border-radius: 3px !important;
            text-align: inherit;
        }

        .form-radio {
            padding-top: 6px;
        }

        .radio-inline {
            font-weight: 500;
        }

        .form-check-input {
            width: 25px;
            height: 25px;
            margin: 0px 6px 2px;
            vertical-align: middle;
        }

        .input-group-text {
            border-right: 0px;
            background-color: #ffffff;
            border-radius: 0.25rem 0 0 0.25rem;
        }

        .input-username > .form-control {
            border-left: 0px;
            border-radius: 0 0.25rem 0.25rem 0;
        }


        @media (max-width: 767px) {
            .img-title {
                display: block;
            }
        }


    </style>
    <style>
        * {
            box-sizing: border-box;
        }

        .container {
            height: 100%;
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }

        .container {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .glow {
            position: absolute;
            width: 300px;
            height: 300px;
            background: linear-gradient(0deg, #000000, #262626);
            border-radius: 50%;
        }

        .glow::before,
        .glow::after {
            content: "";
            position: absolute;
            top: -2px;
            left: -2px;
            background: linear-gradient(
                    45deg,
                    #ff00ee,
                    #0000ff,
                    #00ff00,
                    #ff0000,
                    #ff00ee,
                    #0000ff,
                    #00ff00,
                    #ffff00,
                    #ff0000
            );
            background-size: 400%;
            max-width: calc(300px + 4px);
            max-height: calc(300px + 4px);
            width: calc(300px + 4px);
            height: calc(300px + 4px);
            z-index: -1;
            animation: animate 20s linear infinite;
            border-radius: 50%;
        }

        .disable-animation::before,
        .disable-animation::after {
            animation-play-state: paused;
        }

        .glow::after {
            filter: blur(28px);
        }

        #player,
        #playlist {
            width: 243px;
            height: 212px;
            text-align: center;
            position: relative;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        #songName {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            padding: 0 30px;
        }

        .playlist-btn {
            width: 243px;
            margin-top: 30px;
            text-align: center;
            position: relative;
            left: 50%;
            transform: translateX(-50%);
        }

        .hide {
            display: none;
        }

        #list {
            height: 118px;
            max-height: 118px;
            margin-top: 16px;
            font-size: 12px;
            overflow-x: hidden;
            overflow-y: scroll;
            color: #fff;
            text-align: left;
            padding-left: 8px;
            border: 2px solid #262626;
            border-radius: 5px;
        }

        .list-item {
            line-height: 30px;
            height: 30px;
            margin-top: 4px;
        }

        .list-container button {
            width: 30px;
            padding: 0;
            float: right;
            margin-right: 4px;
        }

        .add-list {
            padding: 4px 6px;
        }

        .wrap-text {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 190px;
            display: inline-block;
        }

        #sourceUrl {
            background: none;
            padding: 8px;
            border: 2px solid #1f1f1f;
            border-radius: 47px;
            outline: none;
            color: white;
            height: 30px;
            width: 192px;
        }

        #sourceUrl:active,
        #sourceUrl:focus {
            border: 2px solid #0088ff;
        }

        .text {
            color: #ffffff;
            display: block;
        }

        button {
            background: #000000;
            color: #ffffff;
            background: linear-gradient(0deg, #000000, #262626);
            font-size: 14px;
            border: none;
            outline: none;
            padding: 0px 15px;
            width: 55px;
            height: 30px;
            line-height: 30px;
            border-radius: 32px;
        }

        button:hover {
            box-shadow: 0 0 8px 0px #ffffff61;
        }

        button:active {
            box-shadow: inset 0 0 6px 0px #ffffff61;
        }

        #seek,
        #volume {
            -webkit-appearance: none;
            border: 1px solid #000000;
            height: 5px;
            vertical-align: middle;
            border-radius: 20px;
            background-color: #232323;
            outline: none;
        }

        #seek::-webkit-slider-thumb,
        #volume::-webkit-slider-thumb {
            -webkit-appearance: none;
            width: 20px;
            height: 20px;
            border: 1px solid #000000;
            border-radius: 10px;
            background: #ffffff;
        }

        #seek {
            display: block;
            width: 230px;
        }

        .scrollbar::-webkit-scrollbar {
            max-width: 5px;
            max-height: 5px;
        }

        .scrollbar::-webkit-scrollbar-thumb {
            border-radius: 10px;
            background: #333;
        }

        .scrollbar::-webkit-scrollbar-thumb:hover {
            box-shadow: inset 0 0 1px 1px #5c6670;
        }

        .scrollbar::-webkit-scrollbar-track:hover {
            border: 1px solid #000000;
            border-radius: 20px;
            background-color: #232323;
        }

        @keyframes animate {
            0% {
                background-position: 0 0;
            }
            50% {
                background-position: 400% 0;
            }
            100% {
                background-position: 0 0;
            }
        }

    </style>
</head>
<body>

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title text-center">Post Gallery<span><a href="{% url 'App_post:home' %}"
                                                                    style="float: right; text-decoration: none; color: #666B7AFF">✖</a></span>
            </h4>
            {% for post in post_list %}
                <hr>
                <div class="row">
                    <div class="form-group col-lg-2 col-md-6 col-sm-12">
                        <small>{{ post.author.first_name }} {{ post.author.last_name }}</small><br>
                        <small>{{ post.author.email }}</small><br>
                        <hr>
                        <small>{{ post.created_on }}</small>
                    </div>
                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <small>{{ post.my_text }}</small>
                    </div>
                    <div class="form-group col-lg-5 col-md-6 col-sm-12">
                        <div class="row">
                            {% if post.post_image1 %}
                                <div class="col-lg-4">
                                    <img src="{{ post.post_image1.url }}" alt="" height="150px"
                                         width="100%">
                                </div>
                            {% endif %}
                            {% if post.post_image2 %}
                                <div class="col-lg-4">
                                    <img src="{{ post.post_image2.url }}" alt="" height="150px"
                                         width="100%">
                                </div>
                            {% endif %}
                            {% if post.post_image3 %}
                                <div class="col-lg-4">
                                    <img src="{{ post.post_image3.url }}" alt="" height="150px"
                                         width="100%">
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group col-lg-1 col-md-6 col-sm-12">
                        <a href="{% url 'App_content:post-react' pk=post.id %}">
                            {% if post.liked_post.liked %}
                                <i class="fa fa-heart"
                               style="float: right; color: #ff0000; font-size: 30px; margin-top: 70%"></i>
                            {% else %}
                                <i class="fa fa-heart-o" aria-hidden="true"
                                   style="float: right; color: #b2acac; font-size: 30px; margin-top: 70%"></i>
                            {% endif %}
                        </a>
                    </div>
                </div>
                <hr>
            {% endfor %}
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

templates/App_content/syllabus_listview.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

</body>
</html>