App_post/urls.py
from django.urls import path
from . import views

app_name = 'App_post'

urlpatterns = [
    path('', views.home, name='home'),
    path('partner-request/', views.partner_request, name='partner-request'),
    path('job-post/', views.job_post, name='job-post'),
    path('display-requests/', views.display_partner_requests, name='display-requests'),
    path('apply/<int:pk>/', views.apply_for_participation, name='apply-for-participation')
]

WePoka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('posts/', include('App_post.urls')),
    path('content/', include('App_content.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class PartnerRequestModel(models.Model):
    title = models.CharField(max_length=500, unique=True)
    type = models.CharField(max_length=100)
    total_participants = models.PositiveIntegerField(blank=False)
    project_duration = models.PositiveIntegerField(blank=False)
    location = models.CharField(max_length=500, blank=False)
    required_skills = models.CharField(max_length=800, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='activity_post_author')
    related_file = models.FileField(upload_to='project_info_files', blank=True, null=True)
    description = models.TextField()
    application_deadline = models.DateTimeField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"{self.title}-{self.status}"


class PartnerApplicationModel(models.Model):
    activity = models.ForeignKey(PartnerRequestModel, on_delete=models.CASCADE, related_name='task')
    participant = models.ForeignKey(User, on_delete=models.CASCADE, related_name='participant')
    reason_of_participation = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"{self.activity.title}-{self.status}"


class JobPostModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='job_post_author')
    job_title = models.CharField(max_length=500)
    company_name = models.CharField(max_length=500)
    position = models.CharField(max_length=400)
    category = models.CharField(max_length=500)
    work_type = models.CharField(max_length=100)
    total_vacancies = models.PositiveIntegerField(blank=False)
    location = models.CharField(max_length=500, blank=False)
    required_skills = models.CharField(max_length=800, blank=False)
    job_description = models.TextField()
    job_responsibilities = models.TextField()
    experience = models.CharField(max_length=100)
    gender_specification = models.CharField(max_length=100, default="Not Specified")
    application_deadline = models.DateTimeField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"{self.job_title}-{self.status}"


class JobApplicationModel(models.Model):
    applied_job = models.ForeignKey(JobPostModel, on_delete=models.CASCADE, related_name='job')
    candidate = models.ForeignKey(User, on_delete=models.CASCADE, related_name='job_candidate')
    reason_of_application = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"{self.applied_job.job_title}-{self.status}"


class CircularModel(models.Model):
    circular_title = models.CharField(max_length=500)
    provider = models.ForeignKey(User, on_delete=models.CASCADE, related_name='circular_provider')
    circular = models.ImageField(upload_to='circulars')
    created_on = models.DateTimeField(auto_now_add=True)

App_post/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse

# Create your views here.
from App_post.models import PartnerRequestModel, JobPostModel, PartnerApplicationModel


def home(request):
    return render(request, 'App_post/home.html')


def partner_request(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        participants = int(request.POST.get('total_participants'))
        location = request.POST.get('location')
        activity_type = request.POST.get('type')
        duration = request.POST.get('project_duration')
        skills = request.POST.get('required_skills')
        deadline = request.POST.get('application_deadline')
        file = request.FILES.get('related_file')
        description = request.POST.get('description')
        request_model = PartnerRequestModel(title=title, type=activity_type, total_participants=participants,
                                            project_duration=duration, location=location,
                                            author=request.user, required_skills=skills,
                                            application_deadline=deadline, related_file=file, description=description)
        request_model.save()
        return HttpResponseRedirect(reverse('App_post:home'))
    return render(request, 'App_post/partner_request.html')


def job_post(request):
    if request.method == 'POST':
        job_title = request.POST.get('job_title')
        company_name = request.POST.get('company_name')
        position = request.POST.get('position')
        work_type = request.POST.get('type')
        vacancies = int(request.POST.get('total_vacancies'))
        category = request.POST.get('category')
        location = request.POST.get('location')
        gender = request.POST.get('gender')
        skills = request.POST.get('required_skills')
        responsibilities = request.POST.get('job_responsibilities')
        description = request.POST.get('job_description')
        deadline = request.POST.get('application_deadline')
        experience = request.POST.get('experience')
        job_model = JobPostModel(author=request.user, job_title=job_title, company_name=company_name, position=position, category=category, work_type=work_type, total_vacancies=vacancies, location=location, required_skills=skills, job_description=description, job_responsibilities=responsibilities, experience=experience, gender_specification=gender, application_deadline=deadline)
        job_model.save()
        return HttpResponseRedirect(reverse('App_post:home'))
    return render(request, 'App_post/job_post.html')


def display_partner_requests(request):
    requests = PartnerRequestModel.objects.all()
    content = {
        'requests': requests,
    }

    return render(request, 'App_post/display_requests.html', context=content)


def apply_for_participation(request, pk):
    project = PartnerRequestModel.objects.get(id=pk)
    if request.method == 'POST':
        reason = request.POST.get('reason')
        apply_model = PartnerApplicationModel(activity=project, participant=request.user, reason_of_participation=reason)
        apply_model.save()
        return HttpResponseRedirect(reverse('App_post:home'))
    return render(request, 'App_post/apply_for_participation.html')

templates/App_post/apply_for_participation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Title</title>
    <style>
        html,
        body {
            height: 100%;
            background-image: url("{% static 'bg_dark.jpg' %}");
        }

        .container-fluid {
            padding: 2rem;
        }

        .card {
            color: #666b7a;
            font-weight: 600;
            border-width: 8px;
            border-color: #444857;
            background-color: #1d1e22;
        }

        .card-body {
            padding: 1rem 2rem;
        }

        .input-daterange > input {
            cursor: pointer;
            border-radius: 3px !important;
            text-align: inherit;
        }

        .form-radio {
            padding-top: 6px;
        }

        .radio-inline {
            font-weight: 500;
        }

        .form-check-input {
            width: 25px;
            height: 25px;
            margin: 0px 6px 2px;
            vertical-align: middle;
        }

        .input-group-text {
            border-right: 0px;
            background-color: #ffffff;
            border-radius: 0.25rem 0 0 0.25rem;
        }

        .input-username > .form-control {
            border-left: 0px;
            border-radius: 0 0.25rem 0.25rem 0;
        }


        @media (max-width: 767px) {
            .img-title {
                display: block;
            }
        }


    </style>
</head>
<body>

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title text-center">Apply For Participation<span><a href="{% url 'App_post:home' %}"
                                                                                      style="float: right; text-decoration: none; color: #666B7AFF">✖</a></span>
            </h4>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                        <label for="reason">Reason Of Participation</label>
                        <textarea type="text" class="form-control" id="reason" name="reason" placeholder="reason" rows="4"></textarea>
                    </div>
                </div>
                <hr>
                <button class="w-100 btn btn-secondary btn-lg" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(".date_range").datepicker({
        todayBtn: "linked",
        autoclose: true,
        todayHighlight: true,
        toggleActive: true
    });

    $("#datepicker").datepicker({
        autoclose: true,
        todayHighlight: true
    });

    $("#phone").mask("(999) 999 9999");

    $("#phone").on("focus click", function () {
        $(this)[0].setSelectionRange(1, 1);
    });

</script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

templates/App_post/display_requests.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>All Requests</title>
    <style>
        html,
        body {
            height: 100%;
            background-image: url("{% static 'bg_dark.jpg' %}");
        }

        .container-fluid {
            padding: 2rem;
        }

        .card {
            color: #ffffff;
            font-weight: 600;
            border-width: 8px;
            border-color: #444857;
            background-color: #1d1e22;
        }

        .card-body {
            padding: 1rem 2rem;
        }

        .input-daterange > input {
            cursor: pointer;
            border-radius: 3px !important;
            text-align: inherit;
        }

        .form-radio {
            padding-top: 6px;
        }

        .radio-inline {
            font-weight: 500;
        }

        .form-check-input {
            width: 25px;
            height: 25px;
            margin: 0px 6px 2px;
            vertical-align: middle;
        }

        .input-group-text {
            border-right: 0px;
            background-color: #ffffff;
            border-radius: 0.25rem 0 0 0.25rem;
        }

        .input-username > .form-control {
            border-left: 0px;
            border-radius: 0 0.25rem 0.25rem 0;
        }


        @media (max-width: 767px) {
            .img-title {
                display: block;
            }
        }


    </style>
</head>
<body>

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h6 class="card-title text-center">All Project / Research Requests</span>
            </h6>
        </div>
    </div>
    {% for r in requests %}
        <div class="card" style="margin-top: 15px;">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-08 col-md-6 col-sm-12">
                        <h6 class="card-title">{{ r.title }} <sup
                                style="font-weight: 200; font-size: 12px">({{ r.type }})</sup></h6>
                        <li style="font-weight: 200; font-size: 14px">Total group members will
                            be: {{ r.total_participants }}</li>
                        <li style="font-weight: 200; font-size: 14px">Duration: {{ r.project_duration }} days</li>
                        <li style="font-weight: 200; font-size: 14px">Location: {{ r.location }}</li>
                        <li style="font-weight: 200; font-size: 14px">Location: {{ r.location }}</li>
                        <li style="font-weight: 200; font-size: 14px">Required Skill-set: {{ r.required_skills }}</li>
                        <li style="font-weight: 200; font-size: 14px">Description: {{ r.description }}</li>
                        <li style="font-weight: 200; font-size: 14px">Application
                            Deadline: {{ r.application_deadline }}</li>
                    </div>
                    <div class="col-lg-04 col-md-6 col-sm-12 form-group"
                         style="text-align: center">
                            <a href="{% url 'App_post:apply-for-participation' pk=r.id %}" class="btn btn-secondary btn-lg" type="submit" style="margin-top: 10px">Apply
                            </a>

                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

templates/App_post/job_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Title</title>
    <style>
        html,
        body {
            height: 100%;
            background-image: url("{% static 'bg_dark.jpg' %}");
        }

        .container-fluid {
            padding: 2rem;
        }

        .card {
            color: #666b7a;
            font-weight: 600;
            border-width: 8px;
            border-color: #444857;
            background-color: #1d1e22;
        }

        .card-body {
            padding: 1rem 2rem;
        }

        .input-daterange > input {
            cursor: pointer;
            border-radius: 3px !important;
            text-align: inherit;
        }

        .form-radio {
            padding-top: 6px;
        }

        .radio-inline {
            font-weight: 500;
        }

        .form-check-input {
            width: 25px;
            height: 25px;
            margin: 0px 6px 2px;
            vertical-align: middle;
        }

        .input-group-text {
            border-right: 0px;
            background-color: #ffffff;
            border-radius: 0.25rem 0 0 0.25rem;
        }

        .input-username > .form-control {
            border-left: 0px;
            border-radius: 0 0.25rem 0.25rem 0;
        }


        @media (max-width: 767px) {
            .img-title {
                display: block;
            }
        }


    </style>
</head>
<body>

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title text-center">Job Post <span><a href="{% url 'App_post:home' %}"
                                                                 style="float: right; text-decoration: none; color: #666B7AFF">✖</a></span>
            </h4>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                        <label for="job_title">Job Title</label>
                        <input type="text" class="form-control" id="job_title" name="job_title" placeholder="Title"/>
                    </div>
                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                        <label for="company_name">Company Name</label>
                        <input type="text" class="form-control" id="company_name" name="company_name"
                               placeholder="Example: Daffodil Groups"/>
                    </div>
                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                        <label for="position">Designation</label>
                        <input type="text" class="form-control" id="position" name="position"
                               placeholder="Example: Senior Manager"/>
                    </div>
                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                        <label for="type">Work Type</label>
                        <div style="margin-top: 10px">
                            <label class="radio-inline">
                                <input id="project" name="type" type="radio" class="form-check-input" value="Remote">Remote
                            </label>
                            <label class="radio-inline">
                                <input id="research" name="type" type="radio" class="form-check-input" value="Onsite">Onsite
                            </label>
                            <label class="radio-inline">
                                <input id="research" name="type" type="radio" class="form-check-input" value="Hybrid">Hybrid
                            </label>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                        <label for="total_vacancies" class="form-label">Total Vacancies</label>
                        <div class="input-group input-username">
                            <input type="number" class="form-control" id="total_vacancies" name="total_vacancies"
                                   placeholder="example: 3">
                        </div>
                    </div>
                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                        <label for="category" class="form-label">Category</label>
                        <input type="text" class="form-control" id="category" name="category"
                               placeholder="Example: IT Department">
                    </div>
                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                        <label for="location" class="form-label">Location</label>
                            <input type="text" class="form-control" id="location"
                                   placeholder="Example: Dhanmondi, Dhaka-1205"
                                   name="location">
                    </div>
                    <div class="form-group col-lg-3 col-md-6 col-sm-12">
                        <label for="gender">Gender Specification</label>
                        <div style="margin-top: 10px">
                            <label class="radio-inline">
                                <input id="Both" name="gender" type="radio" class="form-check-input"
                                       value="Not Specified">Both
                            </label>
                            <label class="radio-inline">
                                <input id="Male" name="gender" type="radio" class="form-check-input"
                                       value="Male">Male
                            </label>
                            <label class="radio-inline">
                                <input id="Female" name="gender" type="radio" class="form-check-input"
                                       value="Female">Female
                            </label>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label for="required_skills" class="form-label">Required Skill-set</label>
                        <div class="input-group input-username">
                            <textarea type="text" class="form-control" id="required_skills" name="required_skills"
                                      placeholder="example: Django, Python, ReactJS" rows="2"></textarea>
                        </div>
                    </div>
                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label for="job_responsibilities" class="form-label">Job Responsibilities</label>
                        <textarea type="text" class="form-control" id="job_responsibilities" name="job_responsibilities"
                                  placeholder="Explain the work" rows="2"></textarea>
                    </div>
                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label for="job_description" class="form-label">Job Description</label>
                        <textarea type="text" class="form-control" id="job_description" placeholder="Description"
                                  name="job_description" rows="2"></textarea>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-6 col-sm-12">
                        <label for="application_deadline" class="form-label">Application Deadline</label>
                        <div class="input-group input-username">
                            <input type="date" class="form-control" id="application_deadline"
                                   name="application_deadline">
                        </div>
                    </div>
                    <div class="form-group col-lg-6 col-md-6 col-sm-12">
                        <label for="experience" class="form-label">Experience</label>
                        <input type="text" class="form-control" id="experience" name="experience"
                               placeholder="Example: 1 year">
                    </div>
                </div>
                <hr>
                <button class="w-100 btn btn-secondary btn-lg" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>